Console.WriteLine("Для отображения строки используются двойные кавычки, это тип string:");
Console.WriteLine("Hello world");
Console.WriteLine("Для отображения литерала используются одинарные кавычки");
Console.WriteLine("это тип char");
Console.WriteLine('b');
Console.WriteLine("Для отображения целочисленного литерала кавычки не нужны");
Console.WriteLine("это тип int");
Console.WriteLine(123);
Console.WriteLine("Для отображения десятичного литерала добавляется m, кавычки не нужны");
Console.WriteLine(12.3m);
Console.WriteLine("Для отображения логического (булевого)");
Console.WriteLine(true);
Console.WriteLine(false);
Console.WriteLine("Все переменные идут в верблюжьем регистре, например:");
Console.WriteLine("char userOption");
Console.WriteLine("int gameScore");
Console.WriteLine("decimal particlesPerMillion");
Console.WriteLine("bool processedCustomer");
string firstName;
firstName = "Bob";
Console.WriteLine("Чтобы получить значение переменной достаточно указать её имя Console.WriteLine без кавычек:");
Console.WriteLine(firstName);
firstName = "Beth";
Console.WriteLine(firstName);
firstName = "Conrad";
Console.WriteLine(firstName);
firstName = "Grant";
Console.WriteLine(firstName);
Console.WriteLine("Удобно в одну строку иниилизировать переменную:");
string secondName = "Ипполитов";
Console.WriteLine(secondName);
Console.WriteLine("Неявно типизированные переменные, объявляются с помощью var");
var message = "HelloWorld";
Console.WriteLine(message);
Console.WriteLine("_______________________________");
Console.WriteLine("_______________________________");
Console.WriteLine("_______________________________");
Console.WriteLine("Сделать вывод сообщения: Hello, Bob! You have 3 messages in your inbox. The temperature is 34.4 celsius.");
Console.WriteLine("Используя 3 переменные Bob,3, 34.4");
Console.WriteLine("_______________________________");
string name = "Bob";
int messages = 3;
decimal temperature = 34.4m;
Console.Write("Hello, " + name);
Console.Write("! You have " + messages);
Console.Write(" messages in your inbox. The temperature is " + temperature);
Console.Write(" celsius.");
Console.WriteLine("");
Console.WriteLine("_______________________________");
Console.WriteLine("_______________________________");
Console.WriteLine("_______________________________");
